### ISSUE TITLE
Satisfy boot keyboard requirements from the spec

### ISSUE THREAD

**Issue by dlkj** [dlkj/usbd-hid-devices#11]
https://www.usb.org/sites/default/files/hid1_11.pdf Appendix B1, F1-5 & G

- [x] Work with Linux, Windows & BIOS #1 
- [x] Implement set_Idle #7 
- [x] Implement set_protocol #9 
- [x] Verify descriptor ordering matches boot spec #10
